name: Build for Deploy

permissions: write-all

on:
  release:
    types: [published]

jobs:
  build:
    name: Build the plugin
    runs-on: windows-latest
    if: ${{ !contains(github.event.head_commit.message, '#no-code') }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Nuget
        uses: iRebbok/setup-nuget@master

      - name: Restore Packages
        run: nuget restore VeryUsualDay.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Get references
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://misaka-zerotwo.github.io/SL-References/Master.zip -OutFile ${{ github.workspace }}/References.zip
          Expand-Archive -Path References.zip -DestinationPath ${{ github.workspace }}\lib

      - name: Build
        run: msbuild VeryUsualDay.sln -p:Configuration=release
        env:
          EXILED_REFERENCES: ${{ github.workspace }}\lib

      - name: Upload artifact and release
        uses: nanoufo/action-upload-artifacts-and-release-assets@main
        with:
          path: ${{ github.workspace }}\bin\Release\VeryUsualDay.dll
          upload-release-files: true
          release-upload-url: ${{ github.event.release.upload_url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    name: Deploy plugin to the server
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: deploy.yml
          workflow_conclusion: success
      - name: Deploy plugin to the server
        uses: rexlmanu/pterodactyl-upload-action@v2.1
        with:
          panel-host: ${{ secrets.PANEL_HOST }}
          api-key: ${{ secrets.API_KEY }}
          server-id: "e40e442f"
          source: "VeryUsualDay.dll"
          target: "./.config/EXILED/Plugins/"
          decompress-target: true